In [18]:
%matplotlib widget
%config InlineBackend.figure_format = 'svg'

In [19]:
import copy
import datetime
import os
import string
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from importlib import reload

import celeri
celeri = reload(celeri)

In [20]:
RUN_NAME = datetime.datetime.now().strftime("%y%m%d%H%M%S") + os.sep
command_file_name = './data/western_north_america/western_north_america_command.json'
command, segment, block, meshes, station, mogi, sar = celeri.read_data(command_file_name)
station = celeri.process_station(station, command)
segment = celeri.process_segment(segment, command)
sar = celeri.process_sar(sar, command)
segment, station, block, mogi, sar = celeri.assign_block_labels(segment, station, block, mogi, sar)
assembly = celeri.create_assembly_dictionary()
assembly = celeri.merge_geodetic_data(assembly, station, sar) 

In [21]:
# celeri.plot_block_labels(segment, block, station)

In [22]:
def euler_pole_covariance_to_rotation_vector_covariance(omega_x, omega_y, omega_z, big_Cov_epoles):
    """
    This function takes the model parameter covariance matrix
    in terms of the Euler pole and rotation rate and linearly
    propagates them to rotation vector space.
    """
    omega_x_sig = np.zeros_like(omega_x)
    omega_y_sig = np.zeros_like(omega_y)
    omega_z_sig = np.zeros_like(omega_z)

    for i in range(len(omega_x)):
        x = omega_x[i]
        y = omega_y[i]
        z = omega_z[i]
        current_idx = (i - 1) * 3 + 1 # TODO: update this index for Python style
#    Cov_epoles = big_Cov_epoles( crnt_idx : crnt_idx + 2 , crnt_idx : crnt_idx + 2);
#    Euler_lon_sig = np.sqrt(Cov_epoles[1, 1])
#    Euler_lat_sig = np.sqrt(Cov_epoles[2, 2])
#    rotation_rate_sig = np.sqrt(Cov_epoles[3, 3])
#    delta_vec_epoles = [ Euler_lat_sig ; Euler_lon_sig ; rotation_rate_sig ];

    """
    There may be cases where x, y and z are all zero.  This leads to /0 errors.  To avoid this  %%
    we check for these cases and Let A = b * I where b is a small constant (10^-4) and I is     %%
    the identity matrix
    """
    if (x == 0) and (y == 0):
        # TODO: Rename A to euler_pole_to_rotation_vector ???
        A = 1e-4 * eye(3)  # Set a default small value for rotation vector uncertainty
    else:
        # Calculate the partial derivatives
        dlat_dx = -z / (x^2 + y^2)^(3/2) / (1 + z^2 / (x^2 + y^2)) * x
        dlat_dy = -z / (x^2 + y^2)^(3/2) / (1 + z^2 / (x^2 + y^2)) * y
        dlat_dz = 1 / (x^2 + y^2)^(1/2) / (1 + z^2 / (x^2 + y^2))
        dlon_dx = -y / x^2 / (1 + (y / x)^2)
        dlon_dy = 1 / x / (1 + (y / x)^2)
        dlon_dz = 0
        dmag_dx = x / sqrt(x^2 + y^2 + z^2)
        dmag_dy = y / sqrt(x^2 + y^2 + z^2)
        dmag_dz = z / sqrt(x^2 + y^2 + z^2)

#       A = [ dlat_dx, dlat_dy, dlat_dz ; ...
#         dlon_dx, dlon_dy, dlon_dz ; ...
#         dmag_dx, dmag_dy, dmag_dz ];


    # Propagate the uncertainties and the new covariance matrix
#    delta_vec_omega = inv(A) * delta_vec_epoles;
        rotation_vector_covariance = np.inv(A) * Cov_epoles * np.inv(A)'

        # Organized data for the return
        diag_vec = np.diag(rotation_vector_covariance);
        omega_x_sig[i] = np.sqrt(diag_vec[0])
        omega_y_sig[i] = np.sqrt(diag_vec[1])
        omega_z_sig[i] = np.sqrt(diag_vec[2])

    return omega_x_sig, omega_y_sig, omega_z_sig


def get_block_constraint_partials(block):
    """
    Partials for a priori block motion constraints.
    Essentially a set of eye(3) matrices
    """
    apriori_block_idx = np.where(block.apriori_flag.to_numpy() == 1)[0]
    print(apriori_block_idx)
    operator = np.zeros((3 * len(apriori_block_idx), 3 * len(block)))
    for i in range(len(apriori_block_idx)):
        start_row = 3 * i
        start_column = 3 * apriori_block_idx[i]
        operator[start_row:start_row+3, start_column:start_column+3] = np.eye(3)
    return operator


def block_constraints(assembly, block, command):
    """
    Applying a priori block motion constraints
    """
    block_constraint_partials = get_block_constraint_partials(block)
    assembly["index"]["block_constraints_idx"] = np.where(block.apriori_flag.to_numpy == 1)[0]
    assembly["data"]["n_block_constraints"] = 3 * len(assembly["index"]["block_constraints_idx"])
    print(block_constraint_partials.shape[0])
    assembly["data"]["block_constraints"] = np.zeros(block_constraint_partials.shape[0])
    assembly["sigma"]["block_constraints"] = np.zeros(block_constraint_partials.shape[0])
    if assembly["data"]["n_block_constraints"] > 0:
        (
            assembly["data"]["block_constraints"][0::3],
            assembly["data"]["block_constraints"][1::3],
            assembly["data"]["block_constraints"][2::3],
        ) = celeri.sph2cart(
            np.deg2rad(block.euler_lon[assembly["index"]["block_constraints_idx"]]),
            np.deg2rad(block.euler_lat[assembly["index"]["block_constraints_idx"]]),
            np.deg2rad(block.rotation_rate[assembly["index"]["block_constraints_idx"]]),
        )

    #    apbcov = stack3([deg_to_rad(Block.eulerLatSig(Index.blockCon)), deg_to_rad(Block.eulerLonSig(Index.blockCon)), deg_to_rad(Block.rotationRateSig(Index.blockCon))])
    #    apbsx, apbsy, apbsz = epoles_cov_to_omega_cov(apbx, apby, apbz, diag(apbcov))
        (
            assembly["sigma"]["block_constraints"][0::3],
            assembly["sigma"]["block_constraints"][1::3],
            assembly["sigma"]["block_constraints"][2::3],
        ) = euler_pole_covariance_to_rotation_vector_covariance(
            assembly["data"]["block_constraints"][0::3],
            assembly["data"]["block_constraints"][1::3],
            assembly["data"]["block_constraints"][2::3],
            diag(apbcov)
        )

    assembly["sigma"]["sigma.block_constraint_weight"] = command["block_constraint_weight"]
    return assembly, block_constraint_partials 

assembly, block_constraint_partials = block_constraints(assembly, block, command)

[29]
3


In [23]:
n_blocks = 3
apriori_block_idx = [0, 2]
operator = np.zeros((3 * len(apriori_block_idx), 3 * n_blocks))
for i in range(len(apriori_block_idx)):
    start_row = 3 * i
    start_column = 3 * apriori_block_idx[i]
    operator[start_row:start_row+3, start_column:start_column+3] = np.eye(3)
print(operator)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [25]:
len(meshes)

2